# Generated by Django 4.2.7 on 2025-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceteam',
            name='company',
            field=models.CharField(default='My Company', help_text="Company name for this team (e.g., 'My Company (San Francisco)')", max_length=200),
        ),
    ]
