# Generated by Django 6.0 on 2025-12-27 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Equipment name (e.g., 'Laptop #123', 'Printer Main Office')", max_length=200)),
                ('serial_number', models.CharField(blank=True, help_text='Unique serial number for identification', max_length=100, null=True, unique=True)),
                ('department', models.CharField(help_text="Department that owns this equipment (e.g., 'IT', 'Operations', 'Sales')", max_length=100)),
                ('location', models.CharField(help_text="Physical location (e.g., 'Building A, Floor 2, Room 205')", max_length=200)),
                ('is_scrapped', models.BooleanField(default=False, help_text='If True, equipment is unusable and cannot have new maintenance requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='Employee currently using this equipment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
                ('maintenance_team', models.ForeignKey(blank=True, help_text='Team responsible for maintaining this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='teams.maintenanceteam')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
