# Generated by Django 6.0 on 2025-12-27 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Computers', 'Software', 'Monitors')", max_length=200, unique=True)),
                ('company', models.CharField(default='My Company (San Francisco)', help_text='Company name for this category', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, help_text='User responsible for this equipment category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
    ]

