# Generated by Django 5.2.9 on 2025-12-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date when equipment was acquired', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Equipment category (e.g., Computers, Software, Monitors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.CharField(default='My Company (San Francisco)', help_text='Company name for this equipment', max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Critical', 'Critical')], default='Good', help_text='Current condition of the equipment', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='has_work_order',
            field=models.BooleanField(default=False, help_text='Whether this equipment has an associated work order'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='used_for',
            field=models.CharField(blank=True, help_text='What this equipment is used for', max_length=200),
        ),
    ]
