# Generated by Django 6.0 on 2025-12-27 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief description of the issue or maintenance task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the issue or maintenance task')),
                ('request_type', models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive')], default='Corrective', help_text='Type of maintenance: Corrective (breakdown) or Preventive (scheduled)', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Scrap', 'Scrap')], default='New', help_text='Current status of the request', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled date/time for preventive maintenance (only for Preventive type)', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to complete the maintenance (in hours)', max_digits=5, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date/time when request was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Technician assigned to this request (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment that needs maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='equipment.equipment')),
                ('maintenance_team', models.ForeignKey(blank=True, help_text='Team responsible for this request (auto-filled from equipment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='teams.maintenanceteam')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
