# Generated by Django 4.2.7 on 2025-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Rejected', 'Rejected'), ('Scrap', 'Scrap')], default='New', help_text='Current status of the request', max_length=20),
        ),
    ]
