# Generated by Django 5.2.9 on 2025-12-27 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_acquisition_date_equipment_category_and_more'),
        ('maintenance', '0002_alter_maintenancerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Due date for completing this maintenance request', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', help_text='Priority level of the maintenance request', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(help_text='Unique work order number', max_length=50, unique=True)),
                ('date', models.DateField(help_text='Date of the work order')),
                ('time', models.TimeField(help_text='Time of the work order')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', help_text='Current status of the work order', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', help_text='Priority level', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the work to be done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee assigned to this work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment this work order is for', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.equipment')),
                ('maintenance_request', models.ForeignKey(blank=True, help_text='Related maintenance request (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the maintenance session')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(blank=True, help_text='End time', null=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per hour for this session', max_digits=10)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours (hrs:mins format)', max_digits=5, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for this session', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(help_text='Work order this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_sessions', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'Maintenance Session',
                'verbose_name_plural': 'Maintenance Sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Inspection', 'Inspection'), ('Repair', 'Repair'), ('Replacement', 'Replacement'), ('Cleaning', 'Cleaning'), ('Calibration', 'Calibration'), ('Testing', 'Testing'), ('Other', 'Other')], help_text='Type of activity performed', max_length=50)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('start_time', models.DateTimeField(help_text='Start time of the activity')),
                ('end_time', models.DateTimeField(blank=True, help_text='End time of the activity', null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of this activity', max_digits=10)),
                ('parts_used', models.TextField(blank=True, help_text='Parts or materials used')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(help_text='Work order this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_time'],
            },
        ),
    ]
